### ISSUE TITLE
Check for dbPool errors in dev API

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polishedapi#2]
- @merlinoa updated `dev` API to use Pool (instead of DBI) at ~5:30 PM June 24
- [ ] Check for error messages:
  - `auth error`
  - `print("successfully reconnection")`
  - `database connection error`

**Comment by phoward38** [comment]
@merlinoa No `auth error` messages in dev API since you changed to dbPool

**Comment by merlinoa** [comment]
@phoward cool let's keep working with the new API using pool only on dev until Thursday and deploy to prod if we don't see any issues by then.

**Comment by merlinoa** [comment]
actually going to merge to master now.  Not still going to hold off on deploying to prod until tomorrow.  Closing this out.

**Comment by phoward38** [comment]
Ask @merlinoa on Tuesday (Jul 7) about updating `polishedapi` version for [Polished Hosted](polished.tech) to use `pool` package instead of `DBI`
  - Ex: `add_account` function

**Comment by phoward38** [comment]
Fixed. Ready to redeploy from @merlinoa
